Architecture:
  Backbone:
    model_size: small
    name: PPLCNetV4
  Head:
    edit_delta_threshold: 0.05
    edit_dropout: 0.2
    edit_gate_threshold: 0.5
    edit_head_dropout: 0.2
    edit_mode: token_refine
    head_list:
    - CTCHead:
        Head:
          fc_decay: 1.0e-05
        Neck:
          depth: 2
          dims: 120
          local_kernel: 7
          mlp_ratio: 2.0
          name: lightsvtr
    - NRTRHead:
        max_text_length: 25
        nrtr_dim: 384
    length_hidden: 128
    length_max: 25
    name: MultiHeadEditRefineNRTR
    nrtr_dim: 384
    nrtr_layers: 4
    train_seed_corrupt_mode: ctc_aware_confusion
    train_seed_corrupt_prob: 0.7
    use_highres_visual: true
    use_length_head: true
    visual_encoder_dropout: 0.1
    visual_encoder_heads: 8
    visual_encoder_layers: 1
    visual_in_channels: 384
    visual_pos_max_height: 4
    visual_pos_max_width: 96
  algorithm: SVTR_LCNet
  model_type: rec
Eval:
  dataset:
    data_dir: /datastore/cndt_thangcpd/linhtruong/workspace5/Data/Indomain_curated/crops/valid
    label_file_list:
    - /datastore/cndt_thangcpd/linhtruong/workspace5/Data/Indomain_curated/crops/valid_label.txt
    name: SimpleDataSet
    transforms:
    - DecodeImage:
        channel_first: false
        img_mode: BGR
    - MultiLabelEncode:
        gtc_encode: NRTRLabelEncode
    - RecResizeImg:
        image_shape:
        - 3
        - 48
        - 320
    - KeepKeys:
        keep_keys:
        - image
        - label_ctc
        - label_gtc
        - length
        - valid_ratio
  loader:
    batch_size_per_card: 128
    drop_last: false
    num_workers: 4
    shuffle: false
Global:
  cal_metric_during_train: true
  calc_epoch_interval: 1
  character_dict_path: ppocr/utils/dict/ppocrv6_dict.txt
  d2s_train_image_shape:
  - 3
  - 48
  - 320
  debug: false
  distributed: false
  epoch_num: 30
  eval_batch_step:
  - 0
  - 200
  freeze_ctc_backbone: true
  infer_mode: false
  log_smooth_window: 20
  max_text_length: 25
  model_name: PP-OCRv6_small_rec
  pretrained_model: /datastore/cndt_thangcpd/linhtruong/workspace5/Data/EditCTC_arbor_runs/curated_runs/e44_highres_ctc_aware_confusion/best_accuracy
  print_batch_step: 10
  save_epoch_step: 1
  save_model_dir: /datastore/cndt_thangcpd/linhtruong/workspace5/Data/EditCTC_arbor_runs/curated_runs/e44_highres_exp1c_fixed_decoupled_4to1
  seed: 1024
  use_gpu: true
  use_space_char: true
Loss:
  gate_mode: random
  gate_percentile: 0.1
  gate_pos_weight: 4.0
  length_max: 25
  loss_config_list:
  - CTCLoss: null
  - LengthLoss: null
  name: MultiLossEditRefineToken
  weight_edit: 1.0
  weight_length: 0.1
  use_decoupled_loss: true
  weight_gate: 0.0
  decoupled_norm: valid
  lambda_fix: 4.0
  lambda_keep: 1.0
Metric:
  main_indicator: acc
  name: RecMetric
Optimizer:
  beta1: 0.9
  beta2: 0.999
  lr:
    learning_rate: 0.0003
    name: Cosine
    warmup_epoch: 2
  name: Adam
  regularizer:
    factor: 0.0001
    name: L2
PostProcess:
  name: CTCLabelDecode
Train:
  dataset:
    data_dir: /datastore/cndt_thangcpd/linhtruong/workspace5/Data/Indomain_curated/crops/train
    ds_width: false
    ext_op_transform_idx: 1
    label_file_list:
    - /datastore/cndt_thangcpd/linhtruong/workspace5/Data/Indomain_curated/crops/train_label.txt
    name: MultiScaleDataSet
    transforms:
    - DecodeImage:
        channel_first: false
        img_mode: BGR
    - RecAug:
        blur_prob: 0.1
        crop_prob: 0.2
        hsv_aug_prob: 0.2
        jitter_prob: 0.2
        noise_prob: 0.2
        reverse_prob: 0.0
        tia_prob: 0.2
    - MultiLabelEncode:
        gtc_encode: NRTRLabelEncode
    - KeepKeys:
        keep_keys:
        - image
        - label_ctc
        - label_gtc
        - length
        - valid_ratio
  loader:
    batch_size_per_card: 64
    drop_last: true
    num_workers: 8
    shuffle: true
  sampler:
    divided_factor:
    - 8
    - 16
    first_bs: 64
    fix_bs: true
    is_training: true
    name: MultiScaleSampler
    scales:
    - - 320
      - 32
    - - 320
      - 48
    - - 320
      - 64
